### ISSUE TITLE
Funky install error

### ISSUE THREAD

**Issue by J35P312** [Clinical-Genomics/loqusdb#49]
Howdy!
I tried to install loqusdb on python 3.6, but I got the  following error:

Obtaining file:///home/jesper/loqusdb2/loqusdb
Requirement already satisfied: click in /home/jesper/miniconda2/envs/py36/lib/python3.6/site-packages (from loqusdb==1.0) (6.7)
Requirement already satisfied: ped_parser in /home/jesper/miniconda2/envs/py36/lib/python3.6/site-packages (from loqusdb==1.0) (1.6.6)
Requirement already satisfied: pymongo>=3.0 in /home/jesper/miniconda2/envs/py36/lib/python3.6/site-packages (from loqusdb==1.0) (3.6.1)
Requirement already satisfied: pytest in /home/jesper/miniconda2/envs/py36/lib/python3.6/site-packages (from loqusdb==1.0) (3.5.1)
Requirement already satisfied: mongomock in /home/jesper/miniconda2/envs/py36/lib/python3.6/site-packages (from loqusdb==1.0) (3.10.0)
Requirement already satisfied: vcftoolbox==1.5 in /home/jesper/miniconda2/envs/py36/lib/python3.6/site-packages (from loqusdb==1.0) (1.5)
Collecting cyvcf2==0.9 (from loqusdb==1.0)
  Using cached https://files.pythonhosted.org/packages/3f/21/29c8dc12e91d55e953f230bf9e96af779b224f6d59f4eacc3dcb80753d34/cyvcf2-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    Collecting cython
      Downloading https://files.pythonhosted.org/packages/19/8e/32b280abb0947a96cdbb8329fb2014851a21fc1d099009f946ea8a8202c3/Cython-0.28.5-cp36-cp36m-manylinux1_x86_64.whl (3.4MB)
    Installing collected packages: cython
    Successfully installed cython-0.28.5
    You are using pip version 10.0.1, however version 18.0 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7d7qgusb/cyvcf2/setup.py", line 64, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'

I can see that cython 0.28.5 is installed, but cyvcf2 seem to be unhappy!
Do you get the same error? What version of cython are you using?

**Comment by J35P312** [comment]
I solved this by  installing cython before loqusdb. Maybe we can update the  install instructions?
